MSEC-47: Update shared Kernels for logging-api (#12)
* MSEC-48: Update shared Kernels for logging-api

updated Masking service

* Enabled steps

* remove test step

* changes pipeline

* updated nuget

diff --git a/.azure/nuget-package.yml b/.azure/nuget-package.yml
--- a/.azure/nuget-package.yml
+++ b/.azure/nuget-package.yml
@@ -25,17 +25,28 @@ parameters:
       - Minor
       - Build
       - Pre-Release
-      
-    # Note: Should only be used once for the initial versioning.
 
 variables:
-  solution: '**/*.sln'
-  buildPlatform: 'Any CPU'
-  buildConfiguration: 'Release'
+- group: nuget-pipeline-secrets
+
+# Define other variables separately
+- name: solution
+  value: '**/*.sln'
+- name: buildPlatform
+  value: 'Any CPU'
+- name: buildConfiguration
+  value: 'Release'
+- name: packageIds
+  value: |
+    MeraStore.Shared.Common.Core: '699ee7dc-f56c-41b4-8689-448d86644287'
+    MeraStore.Shared.Common.Http: '71e4ee16-fb01-4983-9b8f-c4cfdd9ddc78'
+    MeraStore.Shared.Common.Logging: '86070dcc-f2bb-421b-a3ca-b3c5371fa5df'
+    MeraStore.Shared.Common.WebApi: '847345e2-2a60-46cf-b576-e9a66ce1bd4c'
+
 
 jobs:
 - job: BuildAndTest
-  displayName: Build And Test
+  displayName: Restore and Build Project
   variables:
     packageVersion: '' # Placeholder for the calculated version
   steps:
@@ -56,16 +67,8 @@ jobs:
         arguments: '--configuration $(buildConfiguration)'
       condition: succeeded()
 
-    - task: DotNetCoreCLI@2
-      displayName: DotNet Test
-      inputs:
-        command: 'test'
-        projects: '**/${{ parameters.project }}.Tests.csproj'
-        arguments: '--configuration $(buildConfiguration)'
-      condition: succeeded()
-
 - job: CreateNugetPackage
-  displayName: Create Nuget Package
+  displayName: Create NuGet Package
   dependsOn: BuildAndTest
   condition: ne('${{ parameters.versionType }}', 'None')
   variables:
@@ -84,23 +87,37 @@ jobs:
         #!/bin/bash
 
         echo "Starting version calculation..."
-
+        echo "Using the secret: $(System.AccessToken)"
+        
         # Get version type from parameters
         versionType="${{ parameters.versionType }}"
         projectName="${{ parameters.project }}"
-        
+
         echo "Version type selected: $versionType"
         echo "Project selected: $projectName"
 
-        if [[ "$versionType" != "New" ]]; then
-            # Fetch the latest version from NuGet feed
-            nugetSource="https://pkgs.dev.azure.com/sanjyotagureddy/merastore/_packaging/mera-store/nuget/v3/index.json"
-            packageName="MeraStore.Shared.Common.Core"
+        # Get the package ID for the selected project
+        packageIds=$(echo "${{ variables.packageIds }}")
+        packageId=$(echo "$packageIds" | grep -oP "(?<=${projectName}: ').*?(?=')")
 
-            echo "Fetching the latest version for package: $packageName from $nugetSource"
+        if [[ -z "$packageId" ]]; then
+            echo "Error: Package ID for project '$projectName' not found."
+            exit 1
+        fi
+        
+        if [[ "$versionType" != "New" ]]; then
+            ## Fetch the latest version from NuGet feed using the package ID
+           
+            nugetSource="https://feeds.dev.azure.com/sanjyotagureddy/merastore/_apis/packaging/Feeds/merastore/Packages/$packageId"
+
+            echo "Fetching the latest version for package ID: $packageId from $nugetSource"
             
-            # Get the latest version using NuGet API
-            latestVersion=$(curl -s "$nugetSource" | jq -r '.data[] | select(.id=="'"$packageName"'") | .version' | sort -V | tail -n 1)
+
+            response=$(curl -s -H "Authorization: Basic $AZURE_PATH" "$nugetSource")
+            latestVersion=$(echo "$response" | jq -r '.versions[] | select(.isLatest==true) | .version')
+            echo $latestVersion
+            # Print the raw response for debugging
+            echo "Raw response: $response"
 
             # Default to 1.0.0 if no latest version is found
             if [[ -z "$latestVersion" ]]; then
@@ -161,12 +178,14 @@ jobs:
         # Set the calculated version as a pipeline name
         echo "##vso[build.updatebuildnumber]$projectName-$version"
       displayName: 'Calculate Version Number'
+
     - task: DotNetCoreCLI@2
       displayName: DotNet Pack
       inputs:
         command: 'pack'
         packagesToPack: '**/${{ parameters.project }}.csproj'
         arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(packageVersion)'
+
     - task: DotNetCoreCLI@2
       displayName: DotNet Push
       inputs:
